import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import BrightSize from '../components/icons/BrightSize';
import Image from 'next/image';

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Bright Size</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <section className={styles.static}>
            <div className={styles.wrapper}>
              <div className={styles.titleWrapper}>
                <h1>
                  <span>Bright Size </span>
                  <span>Software</span>
                </h1>
              </div>
              <div className={styles.logoWrapper}>
                <BrightSize
                  height={'1.2em'}
                  width={'1.2em'}
                  className={styles.logo}
                />
              </div>
            </div>
          </section>
          <section className={styles.info}>
            <div className={styles.qa}>
              <h2>What we do?</h2>
              <p>
                A family-led Software Engineering Company with proven results in
                web technologies. 🤓
              </p>
            </div>
            <div className={styles.qa}>
              <h2>Where are we?</h2>
              <p>
                We are fully remote - however if you’re curious, we live in and
                love Atlantic Canada. ⛵️
              </p>
            </div>
            <div className={styles.qa}>
              <h2>Who are we?</h2>
              <section className='person'>
                <div className='imageWrapper'>
                  <Image
                    src={require('../assets/ava1.svg')}
                    alt={'photo of Lauchlan Chisholm'}
                    height={100}
                  />
                </div>
                <div className='peopleWrapper'>
                  <p>
                    Lauchlan Chisholm
                    <span className={styles.role}> - President and CEO</span>
                  </p>
                </div>
              </section>
              <section className='person'>
                <div className='imageWrapper'>
                  <Image
                    src={require('../assets/ava2.svg')}
                    alt={'photo of Miranda Chisholm'}
                    height={100}
                  />
                </div>
                <div className='peopleWrapper'>
                  <p>
                    Miranda Chisholm
                    <span className={styles.role}> - Junior Software Dev</span>
                  </p>
                </div>
              </section>
              <section className='person'>
                <div className='imageWrapper'>
                  <Image
                    src={require('../assets/ava3.svg')}
                    alt={'photo of Jordan Ehler'}
                    height={100}
                  />
                </div>
                <div className='peopleWrapper'>
                  <p>
                    Jordan Ehler
                    <span className={styles.role}> - Junior Software Dev</span>
                  </p>
                </div>
              </section>
            </div>
            <div>
              <h2>Projects</h2>
              <p>
                We have had the pleasure of delivering world-class web
                applications. Some are included here.
              </p>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
