import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BrightSize } from "../components/icons";

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Bright Size</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet"></link>
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <section className={styles.static}>
            <h1 className={styles.title}><span>Bright Size </span><span>Software</span></h1>
            {/* <BrightSize /> */}
          </section>
          <section className={styles.info}>
            <div className={styles.qa}>
              <h2>What we do?</h2>
              <p>A family-led Software Engineering Company with proven results in web technologies. 🤓</p>
            </div>
            <div className={styles.qa}>
              <h2>Where are we?</h2>
              <p>We are fully remote - however if you’re curious, we live in and love Atlantic Canada. ⛵️</p>
            </div>
            <div className={styles.qa}>
              <h2>Who are we?</h2>
              <p>Lauchlan Chisholm<span className={styles.role}> - President and CEO</span></p>
              <p>Miranda Chisholm<span className={styles.role}> - Junior Software Dev</span></p>
              <p>Jordan Ehler<span className={styles.role}> - Junior Software Dev</span></p>
            </div>
            <div>
              <h2>Projects</h2>
              <p>We have had the pleasure of delivering world-class web applications. Some are included here.</p>
            </div>
          </section>


        </main>
      </div>
    </>
        );
};

        export default Home;
