import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { BrightSize } from "../components/icons";
import lauchie from "../assets/lauchie.jpg";
import miranda from "../assets/miranda.svg";
import jordan from "../assets/jordan.svg";
import { People } from "../components/molecule/People/People";

const people = [
  {
    id: 1,
    name: "Lauchlan Chisholm",
    role: "President and CEO",
    pic: lauchie,
  },
  {
    id: 2,
    name: "Miranda Chisholm",
    role: "Junior Software Dev",
    pic: miranda,
  },
  {
    id: 3,
    name: "Jordan Ehler",
    role: "Junior Software Dev",
    pic: jordan,
  },
];

const Home: NextPage = () => {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Bright Size</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <section className={styles.static}>
            <div className={styles.wrapper}>
              <div className={styles.titleWrapper}>
                <h1>
                  <span>Bright Size </span>
                  <span>Software</span>
                </h1>
              </div>
              <div className={styles.logoWrapper}>
                <BrightSize
                  height={"1.2em"}
                  width={"1.2em"}
                  className={styles.logo}
                />
              </div>
            </div>
          </section>
          <section className={styles.info}>
            <div className={styles.qa}>
              <h2>What we do?</h2>
              <p>
                A family-led Software Engineering Company with proven results in
                web technologies. 🤓
              </p>
            </div>
            <div className={styles.qa}>
              <h2>Where are we?</h2>
              <p>
                We are fully remote - however if you’re curious, we live in and
                love Atlantic Canada. ⛵️
              </p>
            </div>
            <div className={styles.qa}>
              <h2>Who are we?</h2>
              <People people={people} />
            </div>
            <div>
              <h2>Projects</h2>
              <p>
                We have had the pleasure of delivering world-class web
                applications. Some are included here.
              </p>
            </div>
          </section>
        </main>
      </div>
    </>
  );
};

export default Home;
